# Package information - tells Cargo about this Rust project
[package]
name = "pdm-backend"
version = "0.1.0"
edition = "2021"
description = "Rust backend for PDM Desktop Application - handles hardware communication"
authors = ["Your Name <your.email@example.com>"]

# Dependencies - external libraries this project needs
[dependencies]
# Add dependencies as needed for hardware communication:
# serialport = "4.0"  # For USB/serial communication
# tokio = { version = "1.0", features = ["full"] }  # For async runtime
# serde = { version = "1.0", features = ["derive"] }  # For data serialization
# serde_json = "1.0"  # For JSON serialization

# Binary configuration - tells Cargo how to build the executable
[[bin]]
name = "pdm-backend"
path = "src/main.rs"
